version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/ethereum/go-ethereum
    versions:
    - 1.10.0
    - 1.9.25
  - dependency-name: github.com/labstack/echo/v4
    versions:
    - 4.2.0
  - dependency-name: github.com/spf13/cobra
    versions:
    - 1.1.2
  - dependency-name: github.com/pkg/sftp
    versions:
    - 1.12.0
  - dependency-name: github.com/google/uuid
    versions:
    - 1.2.0
  - dependency-name: github.com/spf13/afero
    versions:
    - 1.5.1
- package-ecosystem: npm
  directory: "/truffle"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: ethers
    versions:
    - 5.0.26
    - 5.0.27
    - 5.0.28
    - 5.0.29
    - 5.0.30
    - 5.0.31
    - 5.0.32
    - 5.1.0
    - 5.1.3
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.0
    - 8.2.1
  - dependency-name: web3
    versions:
    - 1.3.3
    - 1.3.4
  - dependency-name: bn.js
    versions:
    - 5.1.3
- package-ecosystem: npm
  directory: "/ui"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.2
    - 12.6.3
    - 12.7.0
    - 12.7.1
    - 12.7.2
    - 12.7.3
    - 12.8.0
    - 12.8.1
    - 12.8.3
    - 13.0.0
    - 13.0.1
    - 13.0.10
    - 13.0.13
    - 13.0.16
    - 13.0.2
    - 13.0.6
    - 13.0.7
    - 13.1.1
    - 13.1.2
    - 13.1.3
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/react-select"
    versions:
    - 4.0.11
    - 4.0.12
    - 4.0.13
    - 4.0.14
    - 4.0.4
    - 4.0.7
  - dependency-name: swr
    versions:
    - 0.4.0
    - 0.4.1
    - 0.4.2
    - 0.5.0
    - 0.5.2
    - 0.5.3
    - 0.5.4
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.5
