sudo: required

services:
  - docker

language: node_js

cache:
  directories:
    - '$HOME/.npm'

notifications:
  slack:
    rooms:
      - settlemint:5QuOPa3Z4kJbfbNIgei0asur#mint

node_js:
  - '11'

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc

script:
  - npm run build

install:
  - npm ci

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - npx semantic-release
    on:
      all_branches: true
      repo: DataBrokerDAO/dxc

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
