version: "3"

services:
  dxc-server:
    image: databrokerdao/dxc-server:latest
    volumes:
      - ./db-data:/go/db-data
      - ${LOCAL_FILES_DIR}:${LOCAL_FILES_DIR}
    ports:
      - "${PORT}2:8080"
    env_file:
      - .env
  dxc-ui:
    image: databrokerdao/dxc-ui:latest
    ports:
      - "${PORT}:80"`
    env_file:
      - .env
