version: "3"

services:
  dxc-server:
    image: databrokerdao/dxc-server:0.1.3
    volumes:
      - ./db-data:/go/db-data
    ports:
      - "8080:8080"
    env_file:
      - .env
  dxc-ui:
    image: databrokerdao/dxc-ui:0.1.3
    ports:
      - "1337:80"
    env_file:
      - .env
  mqtt-proxy:
    image: databrokerdao/dxc-mqtt-proxy:0.0.1
    ports:
      - 1884:1883
    environment:
      - PORT=1884
      - AUTH_URL=${DXC_SERVER_HOST}/mqtt
    env_file:
      - .env