sudo: required

services:
  - docker

language: node_js

node_js:
  - '11'

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
  - docker pull trufflesuite/ganache-cli:v6.4.3
  - docker run -d -p 8545:8545 -p 7545:8545 --net host trufflesuite/ganache-cli:v6.4.3 -d --mnemonic 'robot robot robot robot robot robot robot robot robot robot robot robot' --defaultBalanceEther '500000000000000'

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - npx semantic-release
    on:
      all_branches: true
      repo: DataBrokerDAO/dxc

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
