version: '3.6'

services:
  rabbit:
    image: 'settlemint/rabbitmq-mqtt:latest'
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_USERNAME
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_PASSWORD
      RABBITMQ_DEFAULT_VHOST: '/'
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 0.9
    restart: always
    ports:
      - '15672:15672'

  mongo:
    image: 'settlemint/mongo:latest'
    command: mongod --replSet replicaset --smallfiles
    volumes:
      - './.mint/mongo:/data/db'
    restart: always

  mongo-replicaset-setup:
    image: 'settlemint/mongo:latest'
    depends_on:
      - 'mongo'
    links:
      - mongo:mongo
    entrypoint: ['./replicaset.sh']

  webserver:
    image: settlemint/mint:latest
    restart: always
    volumes:
      - './.mint/tmp:/tmp'
    ports:
      - '3333:3333'
    env_file:
      - .env
    environment:
      - RUNTIME=WEBSERVER
    depends_on:
      - mongo
      - rabbit
    links:
      - mongo
      - rabbit

  workers:
    image: settlemint/mint:latest
    restart: always
    volumes:
      - './.mint/tmp:/tmp'
    env_file:
      - .env
    environment:
      - RUNTIME=WORKERS
    depends_on:
      - mongo
      - rabbit
    links:
      - mongo
      - rabbit
