info:
  contact:
    name: Databroker
    url: https://github.com/databrokerglobal/dxc/issues
  description: This is the DXC API server
  license:
    name: Settlemint NV
    url: https://github.com/databrokerglobal/dxc/blob/master/dbdao-license.txt
  title: DXC API
  version: "1.0"
paths:
  /files/upload:
    post:
      consumes:
      - multipart/form-data
      description: Link a file from the LOCAL_FILES_DIR to the DXC
      parameters:
      - description: File to Upload
        in: formData
        name: file
        required: true
        type: file
      produces:
      - text/html
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: File invalid or empty
          schema:
            type: string
        "404":
          description: File not found, is the uploaded file in the rigth directory
            or correctly bound to your docker volume?
          schema:
            type: string
        "500":
          description: Error inserting file metadata in database
          schema:
            type: string
      summary: Upload a file
      tags:
      - files
swagger: "2.0"
