info:
  contact:
    name: Databroker Github Repo
    url: https://github.com/databrokerglobal/dxc
  description: Data eXchange Controller API
  license:
    name: License details
    url: https://github.com/databrokerglobal/dxc/blob/master/dbdao-license.txt
  title: DXC
  version: "1.0"
paths:
  /files/download:
    get:
      consumes:
      - application/json
      description: Download a file from the DXC
      parameters:
      - description: File name
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            type: file
        "404":
          description: File not found
          schema:
            type: string
      summary: Download a file
      tags:
      - files
  /files/upload:
    post:
      consumes:
      - multipart/form-data
      description: Link a file from the LOCAL_FILES_DIR to the DXC
      parameters:
      - description: File to Upload
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: File invalid or empty
          schema:
            type: string
        "404":
          description: File not found, is the uploaded file in the rigth directory
            or correctly bound to your docker volume?
          schema:
            type: string
        "500":
          description: Error inserting file metadata in database
          schema:
            type: string
      summary: Upload a file
      tags:
      - files
swagger: "2.0"
